In [2]:
import torch

In [15]:
x = torch.arange(12)
print(x)
print(x.shape)
print(x.numel())

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])
12


In [18]:
X = x.reshape((2,2,3))
print(X)

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])


In [19]:
print(torch.zeros((3, 4)))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [20]:
print(torch.ones((3, 4)))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [26]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
print(x+y)
print(x-y)
print(x/y)
print(x**y)
print(torch.exp(x))

tensor([ 3.,  4.,  6., 10.])
tensor([-1.,  0.,  2.,  6.])
tensor([0.5000, 1.0000, 2.0000, 4.0000])
tensor([ 1.,  4., 16., 64.])
tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])


In [37]:
x = torch.arange(12, dtype=torch.float32).reshape((3,4))
y = torch.tensor([[1,1,4,3], [1,2,3,4], [4,3,2,1]])
print(x.shape)
print(y.shape)
temp = torch.cat((x, y), dim=0)
print(temp.shape)
print(temp)

torch.Size([3, 4])
torch.Size([3, 4])
torch.Size([6, 4])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 1.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])


In [34]:
print(torch.cat((x, y), dim=1))

tensor([[ 0.,  1.,  2.,  3.,  1.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])


In [38]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
print(a)
print(b)

tensor([[0],
        [1],
        [2]])
tensor([[0, 1]])


In [40]:
temp = a+b
print(temp)

tensor([[0, 1],
        [1, 2],
        [2, 3]])
