In [12]:
import torch
import random

In [8]:
# Generate y=Wx+b data
def generate_data(W, b, num_examples):
    X = torch.normal(0, 1, (num_examples, len(W)))
    y = torch.matmul(X, W)+b
    y += torch.normal(0, 0.01, y.shape)
    return X, y

In [9]:
features, labels = generate_data(torch.tensor([2, -3.4]).T, torch.tensor(4.2), 100)

In [10]:
print(features)

tensor([[-0.8281,  0.7953],
        [ 0.5876,  0.4777],
        [-0.5152,  0.0385],
        [-2.5659, -0.5848],
        [-0.0754,  0.4465],
        [-1.1761, -1.1172],
        [-0.8615, -0.6382],
        [-0.7281, -0.1637],
        [ 0.1636, -0.1222],
        [-0.8370, -1.8122],
        [ 1.0097,  0.1611],
        [ 0.5009, -0.4760],
        [ 1.3021,  1.3100],
        [ 0.7787, -0.5913],
        [-0.8352,  1.6314],
        [ 0.6487, -0.1874],
        [-0.7450, -0.2205],
        [-0.1310,  0.6184],
        [-1.3223,  0.7093],
        [-0.7292, -0.1212],
        [-0.1951, -0.2040],
        [ 0.1854, -0.9479],
        [ 0.4164,  1.1154],
        [-0.7495,  0.6869],
        [ 0.5585, -1.3049],
        [ 0.3756,  0.5131],
        [-1.5989,  0.3940],
        [ 0.2093,  0.9080],
        [ 0.0540,  1.1846],
        [ 0.8017,  0.7280],
        [ 0.7474, -0.0382],
        [-0.4612,  0.1450],
        [-0.5728,  1.6576],
        [-0.4530, -0.4497],
        [ 0.1557, -1.0726],
        [-1.1428, -0

In [11]:
print(labels)

tensor([-0.1740,  3.7595,  3.0358,  1.0668,  2.5331,  5.6534,  4.6485,  3.3113,
         4.9320,  8.6991,  5.6927,  6.8140,  2.3487,  7.7728, -3.0184,  6.1185,
         3.4695,  1.8367, -0.8558,  3.1504,  4.5117,  7.8060,  1.2346,  0.3501,
         9.7608,  3.1935, -0.3413,  1.5241,  0.2688,  3.3305,  5.8396,  2.7794,
        -2.5941,  4.8200,  8.1479,  4.9221,  1.8568,  9.9704,  7.9838,  6.5358,
         3.7640,  5.1117,  5.6837,  1.6888,  7.4615,  5.6822, 12.0476,  8.2651,
         4.7043,  2.8264,  1.7235,  8.7693,  4.1285,  4.3971,  5.5790, -6.2689,
         0.0850,  2.5846,  4.1911, -0.5382,  4.9350, 10.5808, 10.6276,  4.9541,
        -0.4110,  2.7913,  0.9791,  6.1886,  2.0103, -0.3356, -2.6599,  7.6712,
         1.8592,  1.3950,  4.3492,  6.2033,  3.7148,  6.3084,  0.7823,  7.7846,
         4.7433,  4.8618, -0.8565,  2.9984,  0.2464,  0.0331,  6.9492,  4.1520,
         1.7343,  3.9115,  2.0933,  9.4348,  4.7647,  3.9908,  9.4374,  1.8314,
        -1.8296, 11.9880,  6.2678,  9.17

In [14]:
def data_iter(batch_size, features, labels):
    num_examples = len(features)
    indices = list(range(num_examples))
    random.shuffle(indices)
    for i in range(0, num_examples, batch_size):
        batch_indices = torch.tensor(indices[i: min(i+batch_size, num_examples)])
        yield features[batch_indices], labels[batch_indices]

In [15]:
batch_size = 10

for X, y in data_iter(20, features, labels):
    print(X)
    print(y)

tensor([[-1.2269, -0.0779],
        [-0.4530, -0.4497],
        [-0.3418,  0.5219],
        [ 0.1201,  0.1560],
        [-1.9581,  0.1849],
        [ 0.1407, -0.0766],
        [-1.0839,  0.3091],
        [-1.8706,  0.9136],
        [ 0.2043,  0.2491],
        [-0.1651, -0.2623],
        [ 0.0540,  1.1846],
        [ 0.3756,  0.5131],
        [ 0.5774,  0.2983],
        [ 1.7826, -0.6518],
        [-0.8015,  0.3564],
        [-0.8304,  2.5919],
        [-0.3086,  1.1719],
        [-0.5789,  0.0677],
        [ 0.6487, -0.1874],
        [ 1.1741, -0.3657]])
tensor([ 2.0103,  4.8200,  1.7343,  3.9115, -0.3356,  4.7433,  0.9791, -2.6599,
         3.7640,  4.7647,  0.2688,  3.1935,  4.3492,  9.9704,  1.3950, -6.2689,
        -0.4110,  2.8264,  6.1185,  7.7846])
tensor([[-0.0760, -1.0004],
        [ 0.1557, -1.0726],
        [-0.0456, -0.6168],
        [ 0.7474, -0.0382],
        [ 0.8017,  0.7280],
        [ 0.5876,  0.4777],
        [-1.4376,  0.1578],
        [ 0.2093,  0.9080],
        [-

In [28]:
W = torch.normal(0, 0.01, size=(1, 2), requires_grad=True).T
b = torch.zeros(1, requires_grad=True)

In [29]:
def linear_model(X, w, b):
    return torch.matmul(X, w) + b

In [30]:
def squared_loss(y_hat, y):
    return (y_hat-y.reshape(y_hat.shape))**2/2

In [31]:
def sgd(params, lr, batch_size):
    with torch.no_grad():
        for para in params:
            para -= lr * para.grad/batch_size
            para.grad.zero_()

In [32]:
lr = 0.03
num_epoches = 3
net = linear_model
loss = squared_loss

for epoch in range(num_epoches):
    for X, y in data_iter(batch_size, features, labels):
        l = squared_loss(linear_model(X, W, b), y)
        l.sum().backward()
